### PR TITLE
add dml.sql

### PR DESCRIPTION
**Pull request by sebshader**
& fix no space in shopping cart

### CODE REVIEW

**Comment by sebshader** [comment]
I ended up taking out making users; it's probably more consistent if we just manually register a user with a set id "user1" before running dml.sql

**Comment by sebshader** [comment]
added optional db/users_dml.sql to gitignore file

**Comment by sebshader** [comment]
@placiak I think I'm understanding what you're saying now: we need a file to populate the database w/ products for users, not just testing. I'll try to do that tomorrow

**Review by placiak — APPROVED** [review]
looks good

**Pull request merged**
